import streamlit as st

st.image("Mind_cloud.jpg")
st.header("Mind Cloud Basic Training Roadmap - 2025")
st.video("viddd.mp4",autoplay=True)

tab1 , tab2 , tab3 , tab4 = st.tabs(["Phase 1 :  Software","Phase 2 :  Hardware and Electronics","Phase 3 :  Microcontroller","Phase 4 :  AI and Computer vision"])
with tab1 :
    st.image("coding.jpg")
    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 1 ] Git and GitHub</h3>',unsafe_allow_html=True)
    st.markdown("#### `Understanding Git & GitHub`")
    st.write("- what is Version control")
    st.write("- Types of version control")
    st.write("- Difference between git and GitHub")
    st.markdown("#### `Main concepts in git`")
    st.write("- Repo ( local Repo - Remote Repo )")
    st.write("- Branch")
    st.write("- Commit")
    st.write("- Clone")
    st.write("- merge")
    st.write("- push")
    st.write("- pull")
    st.write("- pull request")
    st.write("- staging area")
    st.markdown("#### `How to Upload your work using GitHub GUI`")

    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 2 ] Introduction to C++</h3>',unsafe_allow_html=True)
    st.markdown("#### `Introduction to C++`")
    st.write("- what is difference between low and high level languages")
    st.write("- why learn C++ ?")
    st.write("- Data types , Variables , Operators")
    st.write("- Conditional & Control statements")
    st.write("- functions")
    st.write("- built in functions")
    st.markdown("#### `basic data structure`")

    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 2 ] Introduction to python</h3>',unsafe_allow_html=True)
    st.markdown("#### `Introduction to python`")
    st.write("- why learn python ?")
    st.write("- Variables , Operators")
    st.write("- Conditional & Control statements")
    st.write("- Functions ")
    st.write("- lists and lists built in function")
    st.write("- Modules and Imports")
    st.write("- open, write, read files using python")
    st.markdown("#### `Important python libraries`")
    st.write("- Numpy")
    
    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 4 ] Object oriented programming ( oop )</h3>',unsafe_allow_html=True)
    st.markdown("##### -  `Encapsulation`")
    st.markdown("##### -  `Abstraction`")
    st.markdown("##### -  `Inheritance`")
    st.markdown("##### -  `Polymorphism`")
    
with tab2  :
    st.image("electronics_w.jpg")
    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 1 ] Introduction to Electronics</h3>',unsafe_allow_html=True)
    st.markdown("#### `Intro to Hardware`")
    st.write("- what is The Hardware Team ?")
    st.write("- Types of Boards and components")
    st.write("- what is Altium designer ?")
    st.write("- Voltage , Current , Resistance , Power Calculation")
    st.write("- Voltage and Current dividers")
    st.markdown("#### `Basic Devices`")
    st.write("- Resistor and Resistors Types")
    st.write("- Capacitor and Capacitors Types")
    st.write("- Inductors and Inductors Types")
    st.write("- Switches Types")
    st.write("- Power and data connectors")
    st.write("- Diode and Led Types")
    st.markdown("#### `Advanced Devices`")
    st.write("- LDO general overview")
    st.write("- Transistors")
    st.write("- optocoupler")
    st.write("- Voltage Regulators")
    st.write("- Relay")
    st.markdown("#### `Motors and Motors protection`")
    st.write("- Motors introduction")
    st.write("- H bridge")
    
    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">PCB Design</h3>',unsafe_allow_html=True)
    st.write("apply Introduction to Electronics Altium Designer")
    
with tab3 :
    st.image("micro_Contro.jpg")
    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 1 ] Microcontroller Hardware</h3>',unsafe_allow_html=True)
    st.markdown("#### `Introduction to MCs world`")
    st.write("- what is difference between microcontrollers and microprocessors ?")
    st.write("- Microcontrollers Components")
    st.markdown("#### `divie into Micrcontroller`")
    st.write("- sensors and Actuators")
    st.write("- Data signals")
    st.write("- Arduino")
    st.write("- ESP32")
    st.write("- Raspberry PI")
    st.write("- Jetson nano")
    st.write("- STM 32 ")
    st.write("- Communication protocols")
    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 1 ] Microcontroller Software</h3>',unsafe_allow_html=True)
    
with tab4 :
    st.image("AI_IMAGE.jpg")
    st.markdown('<h3 style="background-color:#ADD8E6; color:black; padding:8px; border-radius:6px;">[ 1 ] Introduction to Machine Learning</h3>',unsafe_allow_html=True)
    st.markdown("#### `what is Machine Learning ?`")
    st.write("- what is machine learning ?")
    st.write("- Difference between supervised and unsupervised")
    st.write("- Difference between Classification, Regression")
    st.markdown("#### `LogisticRegression`")
    st.write("- sigmoid function")
    st.write("- How Logistic Regression works")
    st.write("- Logistic Regression using sklearn")
    st.markdown("#### `RandomForest`")
    st.write("- DesisionTree")
    st.write("- RandomForest")
    st.write("- RandomForest using sklearn")
